DevJourney/force-app/main/default/objects/Case_Party__c/Case_Party__c.object-meta.xml
<CustomObject>
    <label>Case Party</label>
    <nameField>
        <label>Case Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Party</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevJourney/force-app/main/default/objects/Case_Party__c/fields/Case_Party__c.field-meta.xml
<CustomField>
    <fullName>Case_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Party</label>
    <referenceTo>Case_Party__c</referenceTo>
    <relationshipLabel>Case Party</relationshipLabel>
    <relationshipName>Case_Party</relationshipName>
    <type>Lookup</type>
</CustomField>

DevJourney/force-app/main/default/objects/Case_Party__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Party</relationshipLabel>
    <relationshipName>Case_Party</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DevJourney/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevJourney/force-app/main/default/objects/Expense__c/fields/Check_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Date__c</fullName>
    <label>Check Date</label>
    <type>Date</type>
</CustomField>

DevJourney/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCIDENT REPORT CC</fullName>
            </value>
            <value>
                <fullName>ACCIDENT REPORT</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATIVE FEE</fullName>
            </value>
            <value>
                <fullName>CD/DVD FEE</fullName>
            </value>
            <value>
                <fullName>CONFERENCE CALL FEE</fullName>
            </value>
            <value>
                <fullName>COPY SERVICE</fullName>
            </value>
            <value>
                <fullName>COURIER</fullName>
            </value>
            <value>
                <fullName>COURT COST</fullName>
            </value>
            <value>
                <fullName>COURT REPORTER</fullName>
            </value>
            <value>
                <fullName>DEPOSITION</fullName>
            </value>
            <value>
                <fullName>EVIDENCE EXPENSE</fullName>
            </value>
            <value>
                <fullName>EXPERT FEE</fullName>
            </value>
            <value>
                <fullName>FAX</fullName>
            </value>
            <value>
                <fullName>FILING FEE</fullName>
            </value>
            <value>
                <fullName>FIRM COST</fullName>
            </value>
            <value>
                <fullName>FOCUS GROUP</fullName>
            </value>
            <value>
                <fullName>INTEREST EXPENSE</fullName>
            </value>
            <value>
                <fullName>INVESTIGATION</fullName>
            </value>
            <value>
                <fullName>INVESTIGATOR FEE</fullName>
            </value>
            <value>
                <fullName>ISO CLAIM SEARCH</fullName>
            </value>
            <value>
                <fullName>MED RECORDS CC</fullName>
            </value>
            <value>
                <fullName>MEDIATION</fullName>
            </value>
            <value>
                <fullName>POSTAGE</fullName>
            </value>
            <value>
                <fullName>PRINTING</fullName>
            </value>
            <value>
                <fullName>PROCESS SERVICE FEE</fullName>
            </value>
            <value>
                <fullName>PROFESSIONAL SERVICES RENDERED</fullName>
            </value>
            <value>
                <fullName>RECORDS</fullName>
            </value>
            <value>
                <fullName>REFUND</fullName>
            </value>
            <value>
                <fullName>SCANNING FEE</fullName>
            </value>
            <value>
                <fullName>TRAVEL EXPENSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevJourney/force-app/main/default/objects/Expense__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Case_Party__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DevJourney/force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevJourney/force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    
    public static List<Account> createAccounts(Integer numAccounts, Boolean isInserted) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numAccounts; i++) {
            Account account = new Account(Name = 'TestAccount' + i);
            accounts.add(account);
        }
        if (isInserted) {
            insert accounts;
        }
        return accounts;
    }
    
    public static List<Contact> createAccountsWithRelatedContacts(Integer numAccounts, Integer numContacts, Boolean isInserted) {
        List<Contact> contacts = new List<Contact>();
        List<Account> accounts = createAccounts(numAccounts, true);
        
        for (Account account : accounts) {
            for(Integer i = 0; i < numContacts; i++) {
                contacts.add(new Contact(
                    LastName = 'Contact' + i,	
                    AccountId = account.Id
                ));
            }
        }  
        if (isInserted) {
            insert contacts;
        }
        return contacts;
    }

    public static List<Expense__c> createExpensesWithCasePartyAndAccount(Id accountId, Id casePartyId, Integer numExpenses, Boolean isInserted) {
        List<Expense__c> expensesList = new List<Expense__c>();
        for (Integer i = 0; i < numExpenses; i++) {
            Expense__c expense = new Expense__c(
                Name = 'Test Expense ' + i,
                Status__c = 'Pending',
                Amount__c = 100,
                Check_Date__c = Date.today(),
                Description__c = 'COPY SERVICE',
                Payee__c = casePartyId
            );
            expensesList.add(expense);
        }

        if (isInserted) {
            insert expensesList;
        }
        return expensesList;
    }

    public static Id createAccount() {
        Account account = new Account(Name = 'Test Account');
        insert account;
        return account.Id;
    }

    public static Id createCaseParty(Id accountId) {
        Case_Party__c payee = new Case_Party__c(
            Name = 'Test Case',
            Parent_Account__c = accountId
        );
        insert payee;
        return payee.Id;
    }

}